### ISSUE TITLE
Error [ERR_REQUIRE_ESM]

### ISSUE THREAD

**Issue by sheldonkotyk** [kraKero/tailwind-fieldtype#1]
I'm stumped and not finding anything relevant.

When running artisan krakero:tailwind-config I get the error:

```
Config file found...
Installing NPM Dependencies...
Converting tailwind config to PHP...
path/vendor/krakero/tailwind-fieldtype/node_modules/@vendeka/tailwind-config-php/index.js:15
const tailwindConfig = require(path.normalize(`${process.cwd()}/${argv.config}`));
                       ^

Error [ERR_REQUIRE_ESM]: require() of ES Module path/tailwind.config.js from path/vendor/krakero/tailwind-fieldtype/node_modules/@vendeka/tailwind-config-php/index.js not supported.
Instead change the require of tailwind.config.js in path/vendor/krakero/tailwind-fieldtype/node_modules/@vendeka/tailwind-config-php/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (path/vendor/krakero/tailwind-fieldtype/node_modules/@vendeka/tailwind-config-php/index.js:15:24) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.6.1
Config file processed!
```

I'm running node 20.6.1 and 1.0.2 of the add-on. Latest Statamic and tailwind.

I tried a clean tailwind.config.js using 

npx tailwindcss init --esm

and same issue.

**Comment by vmitchell85** [comment]
Hey @sheldonkotyk thanks for posting. I don't think I've tried it on NPM 20 yet. I'll give that a go and get back to you.

**Comment by vmitchell85** [comment]
@sheldonkotyk Looks like your `--esm` flag is causing the issue. If you drop that it runs fine.

The default `tailwind.config.js` file that is generated with Statamic looks like this:

```js
module.exports = {
  content: [
    './resources/**/*.antlers.html',
    './resources/**/*.antlers.php',
    './resources/**/*.blade.php',
    './resources/**/*.vue',
    './content/**/*.md'
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
```

I'm open to changes that would work and the default. It seems the error has to do with using `import` vs `require`. Honestly I'm not up to speed on the pros & cons of each and which is best going forward.

I'm going to close this issue, but please comment with any more info or detail. I'd also accept a PR that works for both ways.

**Comment by sheldonkotyk** [comment]
I have no idea what initially caused the tailwind install to use ESM. I was able to get it to work with a different tailwind config. Thanks for your help. Great add-on.

**Comment by sheldonkotyk** [comment]
I ended up switching package.json to use "type": "commonjs", as well.
