### ISSUE TITLE
FR: Open in popup?

### ISSUE THREAD

**Issue by minemindmedia** [kraKero/tailwind-fieldtype#2]
Possible feature request?

New to Statamic here and I really like this add-on. What would be really neat, is if it were possible to open the palette in a popup to select a color, then hide the palette but showing the activate color being used.

When using Bard or similar to build page layouts, the picker takes up a lot of real estate, especially if used multiple times in a layout.

Just an idea!

**Comment by vmitchell85** [comment]
@minemindmedia I like this idea. I'm not sure if I'll have bandwidth for it soon, but I'll try to explore the option.

**Comment by minemindmedia** [comment]
That's awesome!

**Comment by vmitchell85** [comment]
@minemindmedia Hows this look? https://d.pr/v/4VvrPx

**Comment by vmitchell85** [comment]
@minemindmedia Would it be better without the extra button? just show an icon to choose the color?

https://d.pr/v/addpRf

**Comment by vmitchell85** [comment]
Sorry for the multiple posts... @minemindmedia what about this?

https://d.pr/v/vdnhVd

**Comment by minemindmedia** [comment]
Hi @vmitchell85 
Sorry for the late response! Looks great man!
I think any of those would be awesome.

Not sure which one is best. 
I like the simplicity of the 2nd one but maybe having the option to adjust the color after choosing a shade would be most practical?

Either way, it really cleans up the real estate!
